const long MAX_NAME_SIZE = 128;  // Max characters for usernames and group names
const long MAX_MSG_SIZE  = 512;  // Max message text size

struct ChatUser {
  @key string<MAX_NAME_SIZE> username;
  string<MAX_NAME_SIZE>      group;
  @optional string<MAX_NAME_SIZE> firstName;
  @optional string<MAX_NAME_SIZE> lastName;
};

struct ChatMessage {
  string<MAX_NAME_SIZE>      fromUser;
  string<MAX_NAME_SIZE>      toUser;
  string<MAX_NAME_SIZE>      toGroup;
  string<MAX_MSG_SIZE>       message;
  long long                  timestamp_ms;  // Time sent
};

